name: Racket Hygiene
on:
  pull_request:
    branches: [main, master]
jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.12
      with:
        version: 'stable'
    - name: Install racket-format
      run: raco pkg install racket-format
    - name: Check formatting
      run: raco format --check . || (echo "Please run raco format for code hygiene." && exit 1)
